version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bingo
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432